//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Model_.EF_.Sys_
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppAutoSeq
    {
        public int appId { get; set; }
        public string seqKey { get; set; }
        public string seqPrex { get; set; }
        public System.DateTime seqDate { get; set; }
        public int seqDateLength { get; set; }
        public int seqMaxId { get; set; }
        public int seqMaxIdLength { get; set; }
    }
}
