//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Model_.EF_.Sys_
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppDict
    {
        public string dictTypeKey { get; set; }
        public string dictTypeName { get; set; }
        public string dictKey { get; set; }
        public string dictName { get; set; }
        public Nullable<int> dictValue { get; set; }
        public Nullable<int> dictOrder { get; set; }
    }
}
