//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Model_.EF_.Sys_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<App> App { get; set; }
        public virtual DbSet<AppAutoID> AppAutoID { get; set; }
        public virtual DbSet<AppAutoSeq> AppAutoSeq { get; set; }
        public virtual DbSet<AppConfig> AppConfig { get; set; }
        public virtual DbSet<AppConst> AppConst { get; set; }
        public virtual DbSet<AppDict> AppDict { get; set; }
        public virtual DbSet<AppLog> AppLog { get; set; }
        public virtual DbSet<SysAuthority> SysAuthority { get; set; }
        public virtual DbSet<SysFunction> SysFunction { get; set; }
        public virtual DbSet<SysOperation> SysOperation { get; set; }
        public virtual DbSet<SysRole> SysRole { get; set; }
        public virtual DbSet<SysRoleHAuthority> SysRoleHAuthority { get; set; }
        public virtual DbSet<SysRoleHUser> SysRoleHUser { get; set; }
        public virtual DbSet<SysUser> SysUser { get; set; }
    }
}
