//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.POCO_.QY_
{
    using System;
    using System.Collections.Generic;
    
    public partial class QySetNews
    {
        public int id { get; set; }
        public string touser { get; set; }
        public string toparty { get; set; }
        public string totag { get; set; }
        public string msgtype { get; set; }
        public Nullable<int> agentid { get; set; }
        public string newsids { get; set; }
        public Nullable<bool> safe { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public string user_name { get; set; }
        public Nullable<int> send_status { get; set; }
        public Nullable<System.DateTime> send_time { get; set; }
        public string send_msg { get; set; }
    }
}
