//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Model_.EF_.QY_
{
    using System;
    using System.Collections.Generic;
    
    public partial class QyAgentSet
    {
        public int id { get; set; }
        public int agentid { get; set; }
        public string token { get; set; }
        public string aeskey { get; set; }
        public string login_url { get; set; }
        public Nullable<int> logintype { get; set; }
        public bool isdebug { get; set; }
    }
}
