//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Model_.EF_.QY_
{
    using System;
    using System.Collections.Generic;
    
    public partial class QySourceMpNews
    {
        public int id { get; set; }
        public string thumb_media_id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string digest { get; set; }
        public string content_source_url { get; set; }
        public string show_cover_pic { get; set; }
        public System.DateTime add_time { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string update_user_name { get; set; }
    }
}
