//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Model_.EF_.QY_
{
    using System;
    using System.Collections.Generic;
    
    public partial class QyUserConfig
    {
        public int configid { get; set; }
        public string strategy { get; set; }
        public string strategy_name { get; set; }
        public string cfg_key { get; set; }
        public string cfg_name { get; set; }
        public string cfg_type { get; set; }
        public System.DateTime add_time { get; set; }
        public System.DateTime update_time { get; set; }
    }
}
