//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Model_.EF_.QY_
{
    using System;
    using System.Collections.Generic;
    
    public partial class QyUser
    {
        public QyUser()
        {
            this.QyAgent = new HashSet<QyAgent>();
            this.QyDepartment = new HashSet<QyDepartment>();
            this.QyTag = new HashSet<QyTag>();
        }
    
        public string userid { get; set; }
        public string name { get; set; }
        public string department { get; set; }
        public string position { get; set; }
        public string mobile { get; set; }
        public int gender { get; set; }
        public string email { get; set; }
        public string weixinid { get; set; }
        public string avatar { get; set; }
        public Nullable<int> status { get; set; }
        public string extattr { get; set; }
        public Nullable<System.DateTime> syntime { get; set; }
    
        public virtual ICollection<QyAgent> QyAgent { get; set; }
        public virtual ICollection<QyDepartment> QyDepartment { get; set; }
        public virtual ICollection<QyTag> QyTag { get; set; }
    }
}
