//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Model_.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class QyDepartment
    {
        public QyDepartment()
        {
            this.QyUser = new HashSet<QyUser>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int parentid { get; set; }
        public int order { get; set; }
        public System.DateTime syntime { get; set; }
    
        public virtual ICollection<QyUser> QyUser { get; set; }
    }
}
